<?php
    get_header();
?>
    <div id="container">
        <div id="content" role="main">
            <div class="col3-left col3">
                <div>
                    <?php dynamic_sidebar('index-page-col1'); ?>
                </div>
                <div class="clear"></div>
            </div>
            <div class="col3-center col3">
                MIDDLE EARTH HEREMIDDLE EARTH HEREMIDDLE EARTH HEREMIDDLE EARTH HEREMIDDLE EARTH HEREMIDDLE EARTH HEREMIDDLE EARTH HEREMIDDLE EARTH HEREMIDDLE EARTH HEREMIDDLE EARTH HEREMIDDLE EARTH HEREMIDDLE EARTH HEREMIDDLE EARTH HEREMIDDLE EARTH HEREMIDDLE EARTH HEREMIDDLE EARTH HEREMIDDLE EARTH HEREMIDDLE EARTH HEREMIDDLE EARTH HEREMIDDLE EARTH HEREMIDDLE EARTH HEREMIDDLE EARTH HEREMIDDLE EARTH HEREMIDDLE EARTH HEREMIDDLE EARTH HEREMIDDLE EARTH HEREMIDDLE EARTH HEREMIDDLE EARTH HEREMIDDLE EARTH HEREMIDDLE EARTH HEREMIDDLE EARTH HEREMIDDLE EARTH HEREMIDDLE EARTH HEREMIDDLE EARTH HEREMIDDLE EARTH HEREMIDDLE EARTH HEREMIDDLE EARTH HEREMIDDLE EARTH HEREMIDDLE EARTH HEREMIDDLE EARTH HEREMIDDLE EARTH HEREMIDDLE EARTH HEREMIDDLE EARTH HEREMIDDLE EARTH HEREMIDDLE EARTH HEREMIDDLE EARTH HEREMIDDLE EARTH HEREMIDDLE EARTH HEREMIDDLE EARTH HEREMIDDLE EARTH HEREMIDDLE EARTH HEREMIDDLE EARTH HEREMIDDLE EARTH HEREMIDDLE EARTH HEREMIDDLE EARTH HEREMIDDLE EARTH HERE
            </div>
            <div class="col3-right col3">
                <?php dynamic_sidebar('index-page-col3'); ?>
            </div>
        </div><!-- #content -->
    </div><!-- #container -->
<?php
    get_footer();
?>